{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "def test_3():\n>       assert 2 == 3\nE       assert 2 == 3\n\ntest_allure.py:20: AssertionError"}, "start": 1566178128940, "stop": 1566178128941, "uuid": "4674710b-fcfa-4c78-9091-ae4bf12e3423", "historyId": "5afd0dda8524db6b29be91008b13a69f", "fullName": "test_allure#test_3", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "Caizhanyang"}, {"name": "thread", "value": "13896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}